from pyspark.sql.types import *

patient_schema = StructType([
    StructField("Id", StringType(), True),
    StructField("BIRTHDATE", DateType(), True),
    StructField("DEATHDATE", DateType(), True),
    StructField("SSN", StringType(), True),
    StructField("DRIVERS", StringType(), True),
    StructField("PASSPORT", StringType(), True),
    StructField("PREFIX", StringType(), True),
    StructField("FIRST", StringType(), True),
    StructField("MIDDLE", StringType(), True),
    StructField("LAST", StringType(), True),
    StructField("SUFFIX", StringType(), True),
    StructField("MAIDEN", StringType(), True),
    StructField("MARITAL", StringType(), True),
    StructField("RACE", StringType(), True),
    StructField("ETHNICITY", StringType(), True),
    StructField("GENDER", StringType(), True),
    StructField("BIRTHPLACE", StringType(), True),
    StructField("ADDRESS", StringType(), True),
    StructField("CITY", StringType(), True),
    StructField("STATE", StringType(), True),
    StructField("COUNTY", StringType(), True),
    StructField("FIPS", IntegerType(), True),
    StructField("ZIP", IntegerType(), True),
    StructField("LAT", DoubleType(), True),
    StructField("LON", DoubleType(), True),
    StructField("HEALTHCARE_EXPENSES", DoubleType(), True),
    StructField("HEALTHCARE_COVERAGE", DoubleType(), True),
    StructField("INCOME", IntegerType(), True),
])